backend:
  name: github
  branch: master
  repo: tjgilpin/old-rectory
publish_mode: editorial_workflow
media_folder: src/assets/img
public_folder: /assets/img
collections:
  - name: pages
    label: Pages
    folder: src/content/pages
    create: true
    editor:
      preview: false    
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Remove from Navigation", name: "eleventyExcludeFromCollections", widget: "boolean", default: false }
      - { label: "Navigation Order", name: "order", widget: "number", default: 0 }
