backend:
  name: github
  repo: tjgilpin/old-rectory  
  branch: dev
  site_domain: https://dev.old-rectory.pages.dev
  base_url: https://dev.old-rectory.pages.dev
  auth_endpoint: /api/auth
media_folder: src/assets/img
public_folder: /assets/img
collections:
  # Pages Collection (Folder-Based)
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true  # Allow adding new pages
    fields:
      - { label: "Page Title", name: "title", widget: "string" }
      - { label: "Header Images", name: headerimage, widget: image, allow_multiple: true, required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }
      - label: Sections
        name: sections
        widget: list
        required: false
        fields:
          - { label: Section Title, name: title, widget: string, required: false }            
          - { label: Section Image, name: sectionimage, widget: image }              
          - { label: Content, name: body, widget: markdown, required: false }
          - { label: URL, name: url, widget: string, required: false }
          - { label: Link Text, name: cta, widget: string, required: false }
      - label: Gallery Images
        name: gallery
        widget: list
        required: false
        fields:
          - { label: "Gallery Image", name: image, widget: image }
      - label: Additional Options 
        name: additional
        widget: object
        collapsed: true   # 👈 collapsed by default
        fields:
          - { label: "Slug", name: "slug", widget: "string", hint: Customise page URL, required: false }      
          - { label: "Show in Navigation", name: "show", widget: "boolean", default: true, required: false }
          - { label: "Navigation Order", name: "order", widget: "number", default: 10, required: false }
  # Wedding Pages Collection (Folder-Based)
  - name: "wedding"
    label: "Wedding Pages"
    folder: "src/content/weddings"
    create: true  # Allow adding new pages
    fields:
      - { label: "Page Title", name: "title", widget: "string" }
      - { label: "Header Images", name: headerimage, widget: image, allow_multiple: true, required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }
      - label: Sections
        name: sections
        widget: list
        required: false
        fields:
          - { label: Section Title, name: title, widget: string, required: false }            
          - { label: Section Image, name: sectionimage, widget: image }              
          - { label: Content, name: body, widget: markdown, required: false }
          - { label: URL, name: url, widget: string, required: false }
          - { label: Link Text, name: cta, widget: string, required: false }
      - label: Gallery Images
        name: gallery
        widget: list
        required: false
        fields:
          - { label: "Gallery Image", name: image, widget: image }
      - { label: URL, name: url, widget: string, required: false }
      - { label: "Link Text", name: "cta", widget: string, required: false }
      - { label: URL Secondary, name: url_secondary, widget: string, required: false }
      - { label: "Link Secondary Text", name: "cta_secondary", widget: string, required: false }
      - label: Additional Options 
        name: additional
        widget: object
        collapsed: true   # 👈 collapsed by default
        fields:
          - { label: "Slug", name: "slug", widget: "string", hint: Customise page URL, required: false }      
          - { label: "Show in Navigation", name: "show", widget: "boolean", default: true, required: false }
          - { label: "Navigation Order", name: "order", widget: "number", default: 10, required: false }
  # Rooms Pages Collection (Folder-Based)
  - name: "rooms"
    label: "Rooms Pages"
    folder: "src/content/rooms"
    create: true  # Allow adding new pages
    fields:
      - { label: "Page Title", name: "title", widget: "string" }
      - { label: "Header Images", name: headerimage, widget: image, allow_multiple: true, required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }
      - label: Sections
        name: sections
        widget: list
        required: false
        fields:
          - { label: Section Title, name: title, widget: string, required: false }            
          - { label: Section Image, name: sectionimage, widget: image }              
          - { label: Content, name: body, widget: markdown, required: false }
          - { label: URL, name: url, widget: string, required: false }
          - { label: Link Text, name: cta, widget: string, required: false }
      - label: Gallery Images
        name: gallery
        widget: list
        required: false
        fields:
          - { label: "Gallery Image", name: image, widget: image }
      - { label: URL, name: url, widget: string, required: false }
      - { label: "Link Text", name: "cta", widget: string, required: false }
      - { label: URL Secondary, name: url_secondary, widget: string, required: false }
      - { label: "Link Secondary Text", name: "cta_secondary", widget: string, required: false }
      - label: Additional Options 
        name: additional
        widget: object
        collapsed: true   # 👈 collapsed by default
        fields:
          - { label: "Slug", name: "slug", widget: "string", hint: Customise page URL, required: false }      
          - { label: "Show in Navigation", name: "show", widget: "boolean", default: true, required: false }
          - { label: "Navigation Order", name: "order", widget: "number", default: 10, required: false }
  # Food & Drink Pages Collection (Folder-Based)
  - name: "food-drink"
    label: "Food & Drink Pages"
    folder: "src/content/food-drink"
    create: true  # Allow adding new pages
    fields:
      - { label: "Page Title", name: "title", widget: "string" }
      - { label: "Header Images", name: headerimage, widget: image, allow_multiple: true, required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }
      - label: Sections
        name: sections
        widget: list
        required: false
        fields:
          - { label: Section Title, name: title, widget: string, required: false }            
          - { label: Section Image, name: sectionimage, widget: image }              
          - { label: Content, name: body, widget: markdown, required: false }
          - { label: URL, name: url, widget: string, required: false }
          - { label: Link Text, name: cta, widget: string, required: false }
      - label: Gallery Images
        name: gallery
        widget: list
        required: false
        fields:
          - { label: "Gallery Image", name: image, widget: image }
      - { label: URL, name: url, widget: string, required: false }
      - { label: "Link Text", name: "cta", widget: string, required: false }
      - { label: URL Secondary, name: url_secondary, widget: string, required: false }
      - { label: "Link Secondary Text", name: "cta_secondary", widget: string, required: false }
      - label: Additional Options 
        name: additional
        widget: object
        collapsed: true   # 👈 collapsed by default
        fields:
          - { label: "Slug", name: "slug", widget: "string", hint: Customise page URL, required: false }      
          - { label: "Show in Navigation", name: "show", widget: "boolean", default: true, required: false }
          - { label: "Navigation Order", name: "order", widget: "number", default: 10, required: false }
  # Treatment Rooms Pages Collection (Folder-Based)
  - name: "treatment-rooms"
    label: "Treatment Rooms Pages"
    folder: "src/content/treatment-rooms"
    create: true  # Allow adding new pages
    fields:
      - { label: "Page Title", name: "title", widget: "string" }
      - { label: "Header Images", name: headerimage, widget: image, allow_multiple: true, required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }
      - label: Sections
        name: sections
        widget: list
        required: false
        fields:
          - { label: Section Title, name: title, widget: string, required: false }            
          - { label: Section Image, name: sectionimage, widget: image }              
          - { label: Content, name: body, widget: markdown, required: false }
          - { label: URL, name: url, widget: string, required: false }
          - { label: Link Text, name: cta, widget: string, required: false }
      - label: Gallery Images
        name: gallery
        widget: list
        required: false
        fields:
          - { label: "Gallery Image", name: image, widget: image }
      - { label: URL, name: url, widget: string, required: false }
      - { label: "Link Text", name: "cta", widget: string, required: false }
      - { label: URL Secondary, name: url_secondary, widget: string, required: false }
      - { label: "Link Secondary Text", name: "cta_secondary", widget: string, required: false }
      - label: Additional Options 
        name: additional
        widget: object
        collapsed: true   # 👈 collapsed by default
        fields:
          - { label: "Slug", name: "slug", widget: "string", hint: Customise page URL, required: false }      
          - { label: "Show in Navigation", name: "show", widget: "boolean", default: true, required: false }
          - { label: "Navigation Order", name: "order", widget: "number", default: 10, required: false }
  # Upcoming Events Pages Collection (Folder-Based)
  - name: "upcoming-events"
    label: "Upcoming Events Pages"
    folder: "src/content/upcoming-events"
    create: true  # Allow adding new pages
    fields:
      - { label: "Page Title", name: "title", widget: "string" }
      - { label: "Header Images", name: headerimage, widget: image, allow_multiple: true, required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }
      - label: Sections
        name: sections
        widget: list
        required: false
        fields:
          - { label: Section Title, name: title, widget: string, required: false }            
          - { label: Section Image, name: sectionimage, widget: image }              
          - { label: Content, name: body, widget: markdown, required: false }
          - { label: URL, name: url, widget: string, required: false }
          - { label: Link Text, name: cta, widget: string, required: false }
      - label: Gallery Images
        name: gallery
        widget: list
        required: false
        fields:
          - { label: "Gallery Image", name: image, widget: image }
      - { label: URL, name: url, widget: string, required: false }
      - { label: "Link Text", name: "cta", widget: string, required: false }
      - { label: URL Secondary, name: url_secondary, widget: string, required: false }
      - { label: "Link Secondary Text", name: "cta_secondary", widget: string, required: false }
      - label: Additional Options 
        name: additional
        widget: object
        collapsed: true   # 👈 collapsed by default
        fields:
          - { label: "Slug", name: "slug", widget: "string", hint: Customise page URL, required: false }      
          - { label: "Show in Navigation", name: "show", widget: "boolean", default: true, required: false }
          - { label: "Navigation Order", name: "order", widget: "number", default: 10, required: false }
  - label: "Settings & Footer Content"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Header"
        name: "header"
        file: "src/_data/header.yaml"
        fields:
          - { label: "Navigation Logo", name: "navlogo", widget: "image", allow_multiple: false }
          - { label: "Home Logo", name: "homelogo", widget: "image", allow_multiple: false }
          - { label: "Header Image", name: "image", widget: "image", allow_multiple: false }
      - label: Footer Content
        name: footerlinks
        file: "src/_data/footerlinks.yml"
        fields:
          - { label: Address, name: address, widget: markdown }
          - label: Secondary Links
            name: secondary
            widget: list
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
          - label: Social Links
            name: socials
            widget: list
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: SVG Icon, name: icon, widget: text }
              - { label: URL, name: url, widget: string }
          - { label: Newsletter Embed, name: newsletter, widget: markdown, minimal: true }
          - { label: Certification Title, name: certtitle, widget: markdown, minimal: true }
          - { label: Certification Image, name: certimage, widget: image, allow_multiple: false }
          - { label: Copyright, name: copyright, widget: text }
      - label: "Settings"
        name: "settings"          
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Logo", name: "logo", widget: "image", allow_multiple: false }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Locale", name: "locale", widget: "string", default: "en_GB"}
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image", allow_multiple: false }
          - { label: "Image width", name: "width", widget: "number", default: 1200 }          
          - { label: "Image height", name: "height", widget: "number", default: 630 }          
          - { label: "Image alt", name: "alt", widget: "string" }
      - label: "Sitewide Notice"
        name: "sitewide"
        file: "src/_data/notice.yaml"
        fields:
          - { label: "Notice", name: "notice", widget: "markdown" }
          - { label: "Show Notice", name: "show", widget: "boolean", default: false }
      - label: "Treatment Terms"
        name: "treatment"
        file: "src/_data/treatment.yaml"
        fields:
          - { label: "Terms", name: "terms", widget: "markdown" }
          - { label: "Vouchers", name: "vouchers", widget: "markdown" }          
