backend:
  name: github
  repo: tjgilpin/old-rectory  
  branch: main
  site_domain: https://dev.theoldrectoryhastings.co.uk
  base_url: https://dev.theoldrectoryhastings.co.uk
  auth_endpoint: /api/auth
media_folder: src/assets/img
public_folder: /assets/img
collections:
  - label: "Home Pages"
    name: "homepages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/_data/home.yml"
        fields:
          - {label: "Header Image", name: headerimage, widget: image}
          - {label: "Header Logo", name: headerlogo, widget: image}            
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Section Title, name: title, widget: string}            
              - {label: URL, name: url, widget: string}
              - {label: "Section Image", name: sectionimage, widget: image}              
              - { label: Content, name: body, widget: markdown }
              - { label: "Link Text", name: "cta", widget: string }
  # Pages Collection (Folder-Based)
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true  # Allow adding new pages
    filter: {field: "type", value: "page"}    
    fields:
      - { label: "Page Type", name: "type", widget: "select", options: ["page", "subpage"] }
      - { label: "Page Title", name: "title", widget: "string", required: true }
      - { label: "Content", name: "body", widget: "markdown" }     
      - { label: "Remove from Navigation", name: "hide", widget: "boolean", default: false }
      - { label: "Navigation Order", name: "order", widget: "number", default: 10 }
  # Sub Pages Collection (Folder-Based)
  - name: "subpages"
    label: "Sub Pages"
    folder: "src/content/pages"
    create: true  # Allow adding new sub pages
    filter: {field: "type", value: "subpage"}    
    fields:
      - { label: "Page Type", name: "type", widget: "select", options: ["page", "subpage"] }
      - { 
          label: "Parent Page", 
          name: "parent_page", 
          widget: "relation",
          collection: "pages", 
          value_field: "title",  # Stores parent page name directly
          search_fields: ["title"],  # Searchable by title
          display_fields: ["title"]  # Display title in dropdown
        }
      - { label: "Page Title", name: "title", widget: "string", required: true }
      - { label: "Content", name: "body", widget: "markdown" }
  - label: "Settings & Footer Content"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Logo", name: "logo", widget: "image", allow_multiple: false }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Locale", name: "locale", widget: "string", default: "en_GB"}
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image", allow_multiple: false }
          - { label: "Image width", name: "width", widget: "number", default: 1200 }          
          - { label: "Image height", name: "height", widget: "number", default: 630 }          
          - { label: "Image alt", name: "alt", widget: "string" }
      - label: "Footer Content"
        name: "footerlinks"
        file: "src/_data/footerlinks.yaml"
        fields:
          - label: Footer Links
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }