backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: tjgilpin/11ty-decap-netlify
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Pages"
    name: "pages"
    folder: "src/pages"
    create: true
    editor:
      preview: false    
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Remove from Navigation", name: "eleventyExcludeFromCollections", widget: "boolean", default: false }
      - { label: "Navigation Order", name: "order", widget: "number", default: 0 }
  - label: "Posts"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Post Listing Page"
    name: "posts"
    files:
      - label: "About Page"
        name: "about"
        file: "src/posts.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" } 
          - { label: "Posts URL", name: "posts", widget: "string" }
          - { label: "Navigation Order", name: "postsorder", widget: "number" }        
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Logo", name: "logo", widget: "image", allow_multiple: false }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Locale", name: "locale", widget: "string", default: "en_GB", hint: "To infinity and beyond!" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image", allow_multiple: false }
          - { label: "Image width", name: "width", widget: "number", default: 1200 }          
          - { label: "Image height", name: "height", widget: "number", default: 630 }          
          - { label: "Image alt", name: "alt", widget: "string" }
      - label: "Footer Links"
        name: "footerlinks"
        file: "src/_data/footerlinks.yaml"
        fields:
          - label: Footer Links
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
